In [1]:
import numpy as np
import sys

In [3]:
print('sys version: {}\r\nnumpy version: {}'.format(sys.version, np.__version__))

sys version: 3.6.5 |Anaconda custom (64-bit)| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
numpy version: 1.14.5


In [19]:
x = np.array((1,2,3), dtype=np.int)
x

array([1, 2, 3])

In [28]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [29]:
y = np.ones((3,3))
np.dot(x,y)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [30]:
x*y

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [34]:
x = np.arange(9).reshape(3,3).T
x

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [37]:
np.tan(0)

0.0